CREATE DATABASE tarefa01;
SHOW DATABASES;
USE tarefa01;

CREATE TABLE CadFun (
	CODFUN INTEGER NOT NULL PRIMARY KEY,
    NOME VARCHAR(40) NOT NULL,
    DEPTO CHAR(2),
    FUNCAO CHAR(20),
    SALARIO DECIMAL(10,2)
);

SHOW TABLES;

DESCRIBE CadFun;
DESCRIBE CadFun CODFUN;

#INSERÇÃO DE REGISTROS
INSERT INTO CadFun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (12, 'CARLOS ALBERTO', '3', 'VENDEDOR', 1530.00);
INSERT INTO CadFun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (15, 'MARCOS HENRIQUE', '2', 'GERENTE', 1985.75);
INSERT INTO CadFun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (7, 'APARECIDA SILVA', '3', 'SECRETARIA', 1200.50);

INSERT INTO CadFun (CODFUN, NOME, DEPTO, SALARIO) VALUES (44, 'JACIBA DA SILVA', '3', 1500.00);
INSERT INTO CadFun VALUES (2, 'WILSON DE MACEDO', '3', 'PROGRAMADOR', 1050.00);
INSERT INTO CadFun VALUES (5, 'AUGUSTO SOUZA', '3', 'PROGRAMADOR', 1050.00);

#CONSULTA DE REGISTROS
SELECT * FROM CadFun;
SELECT NOME, CODFUN FROM CadFun WHERE DEPTO = '3';
SELECT NOME, SALARIO FROM CadFun ORDER BY NOME;
SELECT NOME, SALARIO FROM CadFun ORDER BY NOME DESC;
SELECT DEPTO, NOME FROM CadFun ORDER BY DEPTO, NOME;
SELECT DEPTO, NOME FROM CadFun ORDER BY DEPTO, NOME DESC;
SELECT NOME FROM CadFun WHERE DEPTO = '3' ORDER BY NOME;

#ALTERAÇÃO DE REGISTROS
#INSERÇÃO DA ANA BASTOS DO DEPARTAMENTO 5
INSERT INTO CadFun (CODFUN, DEPTO, NOME) VALUES ('6', '5', 'ANA BASTOS');

SELECT * FROM CadFun WHERE CODFUN = 7;
UPDATE CadFun SET SALARIO = 2300.56 WHERE CODFUN = 7;
SELECT * FROM CadFun WHERE CODFUN = 7;
SELECT * FROM CadFun WHERE NOME = 'ANA BASTOS';

SET SQL_SAFE_UPDATES = 0;
UPDATE CadFun SET DEPTO = '3' WHERE NOME = 'ANA BASTOS';
SELECT * FROM CadFun WHERE NOME = 'ANA BASTOS';
SELECT * FROM CadFun;
UPDATE CadFun SET SALARIO = SALARIO * 1.10;
SELECT * FROM CadFun;

#EXCLUSÃO DE REGISTROS
SELECT * FROM CadFun;
SELECT DISTINCT DEPTO FROM CadFun;
DELETE FROM CadFun WHERE DEPTO = '2';
SELECT * FROM CadFun;
SELECT DISTINCT DEPTO FROM CadFun;

#INSERÇÃO E EXCLUSÃO DO FUNCIONÁRIO MARCELO SOUZA
INSERT INTO CadFun (CODFUN, NOME, DEPTO, FUNCAO, SALARIO) VALUES (1, 'MARCELO SOUZA', '3', 'PROGRAMADOR', 1412.10);
DELETE FROM CadFun WHERE NOME = 'MARCELO SOUZA';

SELECT * FROM CadFun;

TRUNCATE TABLE CadFun;

#ALTERAÇÃO NA ESTRUTURA DA TABELA
ALTER TABLE CadFun ADD ADMISSAO DATE;
SELECT * FROM CadFun;

UPDATE CadFun SET ADMISSAO = '2006-01-15' WHERE CODFUN = 2;
UPDATE cadfun SET ADMISSAO = '1999-10-21' WHERE CODFUN = 3;
UPDATE cadfun SET ADMISSAO = '2004-10-21' WHERE CODFUN = 4;
UPDATE cadfun SET ADMISSAO = '2006-04-26' WHERE CODFUN = 5;
UPDATE cadfun SET ADMISSAO = '1980-05-10' WHERE CODFUN = 7;
UPDATE cadfun SET ADMISSAO = '1999-12-15' WHERE CODFUN = 9;
UPDATE cadfun SET ADMISSAO = '2000-12-21' WHERE CODFUN = 12;
UPDATE cadfun SET ADMISSAO = '2000-10-21' WHERE CODFUN = 25;
SELECT * FROM cadfun;

#TESTE CAMPO DATA
SELECT NOME, ADMISSAO FROM cadfun where month(admissao) = 12;
SELECT NOME, ADMISSAO FROM cadfun WHERE ADMISSAO >= '2000-01-01';

#PREPARAÇÃO PARA PRÓXIMOS EXERCÍCIOS
INSERT INTO CadFun VALUES (15, 'MARCOS HENRIQUE', '2', 'GERENTE', 2184.33, '2006-05-25');
INSERT INTO CadFun VALUES (20, 'AUDREY TOLEDO', '2', 'SUPERVISORA', 1700.00, '2006-07-05');
INSERT INTO CadFun VALUES (22, 'SANDRA MANZANO', '2','ANALISTA', 2000.00, '2006-07-01');
INSERT INTO CadFun VALUES (24, 'MARCIO CANUTO', '2', 'PROGRAMADOR', 1200.00, '2006-07-10');
SELECT * FROM CadFun;

#CONSULTAS COM OPERADORES ARITMÉTICOS
SELECT NOME, SALARIO FROM CadFun;
SELECT NOME, SALARIO + 100 FROM CadFun;
SELECT NOME, SALARIO FROM CadFun;
SELECT NOME, SALARIO * 1.20 FROM CadFun;
SELECT NOME, SALARIO FROM CadFun;

#CONSULTAS COM OPERADORES DE COMPARAÇÃO OU RELACIONAIS
SELECT * FROM CadFun WHERE DEPARTAMENTO = ‘5’;
SELECT * FROM CadFun WHERE FUNCAO = 'VENDEDOR';
SELECT * FROM CadFun WHERE SALARIO <= 1700;
SELECT * FROM CadFun WHERE SALARIO > 1700 + 50;
SELECT * FROM CadFun WHERE SALARIO > (1700 + 50);

#CONSULTAS COM OPERADORES LOGICOS
SELECT * FROM CadFun WHERE (DEPARTAMENTO = '3') AND (FUNCAO = 'PROGRAMADOR');
SELECT * FROM CadFun WHERE (DEPARTAMENTO = '3') OR (DEPARTAMENTO = '5');
SELECT * FROM CadFun WHERE NOT (FUNCAO = 'VENDEDOR');
SELECT * FROM CadFun WHERE (DEPARTAMENTO = '5') XOR (FUNCAO = 'PROGRAMADOR');

#CONSULTAS COM OPERADORES ADICIONAIS
ALTER TABLE CadFun ADD FILHOS SMALLINT;
ALTER TABLE morto ADD FILHOS SMALLINT;
SELECT NOME, FILHOS FROM CadFun;
SELECT CODFUN, NOME, FILHOS FROM CadFun WHERE FILHOS IS NULL;
SELECT CODFUN, NOME, FILHOS FROM CadFun WHERE NOT FILHOS IS NULL;
SELECT CODFUN, NOME, FILHOS FROM CadFun WHERE FILHOS IS NOT NULL;
SELECT CODFUN, NOME, FILHOS FROM CadFun WHERE NOT (FILHOS IS NULL);

UPDATE CadFun SET FILHOS = 1 WHERE CODFUN = 2;
UPDATE CadFun SET FILHOS = 3 WHERE CODFUN = 3;
UPDATE CadFun SET FILHOS = 2 WHERE CODFUN = 5;
UPDATE CadFun SET FILHOS = 1 WHERE CODFUN = 9;
UPDATE CadFun SET FILHOS = 4 WHERE CODFUN = 20;
UPDATE CadFun SET FILHOS = 3 WHERE CODFUN = 25;
SELECT CODFUN, NOME, FILHOS FROM CadFun;
SELECT CODFUN, NOME, FILHOS FROM CadFun WHERE FILHOS IS NULL;
SELECT CODFUN, NOME, FILHOS FROM CadFun WHERE NOT (FILHOS IS NULL);
SELECT * FROM CadFun WHERE SALARIO BETWEEN 1700 AND 2000;
SELECT * FROM CadFun WHERE SALARIO NOT BETWEEN 1700 AND 2000;
SELECT * FROM CadFun WHERE DEPARTAMENTO IN ('2', '3');
SELECT * FROM CadFun WHERE DEPARTAMENTO NOT IN ('2', '3');

#OPERADOR LIKE
SELECT * FROM CadFun WHERE NOME LIKE 'A%';
SELECT * FROM CadFun WHERE NOME LIKE '_A%';
SELECT * FROM CadFun WHERE NOME LIKE '%AN%';
SELECT * FROM CadFun WHERE SALARIO LIKE '%6';
SELECT * FROM CadFun WHERE SALARIO LIKE '_5%2';
SELECT * FROM CadFun WHERE NOME NOT LIKE '%AN%';
